"""
Document Creator - Create various types of documents
"""

import asyncio
import logging
from typing import Dict, Any, List, Optional
from datetime import datetime
import json

class DocumentCreator:
    """Create documents in various formats"""
    
    def __init__(self):
        self.logger = logging.getLogger(__name__)
        self.templates = self.load_templates()
        
    def load_templates(self) -> Dict[str, Any]:
        """Load document templates"""
        return {
            "report": {
                "title": "Research Report",
                "sections": ["Executive Summary", "Introduction", "Methodology", "Findings", "Conclusion"],
                "format": "markdown"
            },
            "technical_spec": {
                "title": "Technical Specification",
                "sections": ["Overview", "Requirements", "Architecture", "Implementation", "Testing"],
                "format": "markdown"
            },
            "meeting_notes": {
                "title": "Meeting Notes",
                "sections": ["Attendees", "Agenda", "Discussion", "Action Items", "Next Steps"],
                "format": "markdown"
            },
            "project_plan": {
                "title": "Project Plan",
                "sections": ["Objectives", "Timeline", "Resources", "Milestones", "Risks"],
                "format": "markdown"
            }
        }
        
    async def create_document(self, doc_type: str, content: Dict[str, Any], 
                            output_format: str = "markdown") -> Dict[str, Any]:
        """Create a document"""
        self.logger.info(f"Creating {doc_type} document in {output_format} format")
        
        try:
            if doc_type not in self.templates:
                return {"error": f"Document type {doc_type} not supported"}
                
            template = self.templates[doc_type]
            
            # Generate document content
            if output_format == "markdown":
                document = await self.create_markdown_document(template, content)
            elif output_format == "html":
                document = await self.create_html_document(template, content)
            elif output_format == "json":
                document = await self.create_json_document(template, content)
            else:
                return {"error": f"Output format {output_format} not supported"}
                
            return {
                "status": "created",
                "document_type": doc_type,
                "format": output_format,
                "content": document,
                "created_at": datetime.now().isoformat(),
                "size": len(document.encode('utf-8'))
            }
            
        except Exception as e:
            self.logger.error(f"Document creation failed: {e}")
            return {"error": str(e)}
            
    async def create_markdown_document(self, template: Dict[str, Any], content: Dict[str, Any]) -> str:
        """Create a markdown document"""
        lines = []
        
        # Title
        title = content.get("title", template["title"])
        lines.append(f"# {title}")
        lines.append("")
        
        # Metadata
        lines.append(f"**Created:** {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
        if content.get("author"):
            lines.append(f"**Author:** {content['author']}")
        if content.get("version"):
            lines.append(f"**Version:** {content['version']}")
        lines.append("")
        
        # Sections
        sections = content.get("sections", {})
        for section_name in template["sections"]:
            lines.append(f"## {section_name}")
            lines.append("")
            
            # Add content for this section
            section_content = sections.get(section_name, "")
            if isinstance(section_content, str):
                lines.append(section_content)
            elif isinstance(section_content, list):
                for item in section_content:
                    lines.append(f"- {item}")
            elif isinstance(section_content, dict):
                for key, value in section_content.items():
                    lines.append(f"**{key}:** {value}")
            
            lines.append("")
            
        # Additional content
        if content.get("additional_content"):
            lines.append("## Additional Information")
            lines.append("")
            lines.append(content["additional_content"])
            lines.append("")
            
        # Footer
        lines.append("---")
        lines.append(f"*Generated by ODIN-INFO Document Creator*")
        
        return "\n".join(lines)
        
    async def create_html_document(self, template: Dict[str, Any], content: Dict[str, Any]) -> str:
        """Create an HTML document"""
        title = content.get("title", template["title"])
        
        html_parts = []
        html_parts.append(f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <style>
        body {{ font-family: Arial, sans-serif; margin: 40px; line-height: 1.6; }}
        h1 {{ color: #333; border-bottom: 2px solid #333; padding-bottom: 10px; }}
        h2 {{ color: #555; margin-top: 30px; }}
        .metadata {{ background-color: #f4f4f4; padding: 15px; border-radius: 5px; margin: 20px 0; }}
        .section {{ margin: 20px 0; }}
        .footer {{ margin-top: 40px; padding-top: 20px; border-top: 1px solid #ccc; font-size: 0.9em; color: #666; }}
    </style>
</head>
<body>""")
        
        # Title
        html_parts.append(f"<h1>{title}</h1>")
        
        # Metadata
        html_parts.append("<div class='metadata'>")
        html_parts.append(f"<strong>Created:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}<br>")
        if content.get("author"):
            html_parts.append(f"<strong>Author:</strong> {content['author']}<br>")
        if content.get("version"):
            html_parts.append(f"<strong>Version:</strong> {content['version']}<br>")
        html_parts.append("</div>")
        
        # Sections
        sections = content.get("sections", {})
        for section_name in template["sections"]:
            html_parts.append("<div class='section'>")
            html_parts.append(f"<h2>{section_name}</h2>")
            
            section_content = sections.get(section_name, "")
            if isinstance(section_content, str):
                html_parts.append(f"<p>{section_content}</p>")
            elif isinstance(section_content, list):
                html_parts.append("<ul>")
                for item in section_content:
                    html_parts.append(f"<li>{item}</li>")
                html_parts.append("</ul>")
            elif isinstance(section_content, dict):
                html_parts.append("<dl>")
                for key, value in section_content.items():
                    html_parts.append(f"<dt><strong>{key}:</strong></dt>")
                    html_parts.append(f"<dd>{value}</dd>")
                html_parts.append("</dl>")
            
            html_parts.append("</div>")
            
        # Footer
        html_parts.append("<div class='footer'>")
        html_parts.append("<hr>")
        html_parts.append("<em>Generated by ODIN-INFO Document Creator</em>")
        html_parts.append("</div>")
        
        html_parts.append("</body></html>")
        
        return "\n".join(html_parts)
        
    async def create_json_document(self, template: Dict[str, Any], content: Dict[str, Any]) -> str:
        """Create a JSON document"""
        document = {
            "metadata": {
                "title": content.get("title", template["title"]),
                "created_at": datetime.now().isoformat(),
                "type": "document",
                "template": template["title"]
            },
            "sections": content.get("sections", {}),
            "additional_content": content.get("additional_content", "")
        }
        
        # Add author and version if provided
        if content.get("author"):
            document["metadata"]["author"] = content["author"]
        if content.get("version"):
            document["metadata"]["version"] = content["version"]
            
        return json.dumps(document, indent=2)
        
    async def create_summary(self, research_data: Dict[str, Any], credible_sources: List[Dict[str, Any]]) -> str:
        """Create a summary document from research data"""
        content = {
            "title": f"Research Summary: {research_data['topic']}",
            "sections": {
                "Executive Summary": f"Research conducted on {research_data['topic']} with {research_data['source_count']} sources analyzed.",
                "Key Findings": research_data.get("synthesis", {}).get("main_points", []),
                "Sources": [f"{source['title']} ({source['url']})" for source in credible_sources[:5]]
            }
        }
        
        result = await self.create_document("report", content, "markdown")
        return result.get("content", "")
