"""
ODIN-Hunter | Report Builder
Builds professional, platform-ready bug bounty reports
"""

import os
from datetime import datetime
from jinja2 import Template
from reporter.severity_classifier import SeverityClassifier
from ai_engine.claude_hunter import ClaudeHunter

REPORT_TEMPLATE = """# {{ title }}

## Summary
{{ description }}

## Severity
**{{ severity | upper }}** (CVSS: {{ cvss_score }})

## Affected Asset
`{{ target }}`

## Vulnerability Type
{{ type }}

## Steps to Reproduce
{% for step in poc_steps %}
{{ loop.index }}. {{ step }}
{% endfor %}

## Proof of Concept
{% if proof.url %}
**Request URL:** `{{ proof.url }}`
{% endif %}
{% if proof.payload %}
**Payload Used:** `{{ proof.payload }}`
{% endif %}
{% if proof.response_snippet %}
**Server Response:**
```
{{ proof.response_snippet }}
```
{% endif %}

## Impact
{{ impact }}

## Remediation
{{ remediation }}

## Additional Notes
Report generated by ODIN-Hunter on {{ timestamp }}.
"""

class ReportBuilder:
    def __init__(self):
        self.classifier = SeverityClassifier()
        self.claude = ClaudeHunter()
        self.template = Template(REPORT_TEMPLATE)

    async def build(self, finding: dict, target: str, platform: str) -> dict:
        """Build a complete, professional bug report"""
        # Classify severity
        cvss = self.classifier.calculate_cvss(finding)
        severity = finding.get("severity", "medium")

        # Generate impact statement
        impact = self._generate_impact(finding)

        # Get PoC steps
        poc_steps = finding.get("poc_steps", [])
        if not poc_steps:
            poc_steps = await self._generate_poc_steps(finding)

        # Render report body
        body = self.template.render(
            title=finding.get("title", "Vulnerability Report"),
            description=finding.get("description", ""),
            severity=severity,
            cvss_score=cvss.get("score", "N/A"),
            target=target,
            type=finding.get("type", ""),
            poc_steps=poc_steps,
            proof=finding.get("proof", {}),
            impact=impact,
            remediation=finding.get("remediation", ""),
            timestamp=datetime.now().strftime("%Y-%m-%d %H:%M UTC")
        )

        report = {
            "title": finding.get("title"),
            "body": body,
            "severity": severity,
            "cvss": cvss,
            "target": target,
            "platform": platform,
            "finding_type": finding.get("type"),
            "estimated_bounty_min": finding.get("estimated_bounty_min", 0),
            "estimated_bounty_max": finding.get("estimated_bounty_max", 0),
            "created_at": datetime.now().isoformat(),
            "status": "draft"
        }

        print(f"[ReportBuilder] Built report: {report['title']} [{severity}]")
        return report

    def _generate_impact(self, finding: dict) -> str:
        finding_type = finding.get("type", "")
        severity = finding.get("severity", "medium")

        impact_map = {
            "sql_injection": "An attacker could read, modify, or delete database contents, bypass authentication, and potentially gain remote code execution on the database server.",
            "xss": "An attacker could steal session cookies, redirect users to malicious sites, perform actions on behalf of victims, or deliver malware.",
            "ssrf": "An attacker could access internal services, cloud metadata (including credentials), and potentially pivot to internal infrastructure.",
            "idor": "An attacker could access, modify, or delete data belonging to other users, leading to data breach and privacy violation.",
            "auth_bypass": "An attacker could gain unauthorized access to the application, impersonate users or administrators, and access sensitive functionality.",
            "secret_exposure": "Exposed credentials could allow an attacker to access backend systems, third-party services, or cloud infrastructure.",
            "graphql_introspection": "An attacker can enumerate the entire API schema, discover internal data structures, and identify additional attack vectors.",
            "jwt_none_algorithm": "An attacker can forge authentication tokens and impersonate any user including administrators without knowing any secret.",
        }

        return impact_map.get(finding_type, f"This {severity}-severity vulnerability could allow an attacker to compromise the confidentiality, integrity, or availability of the application.")

    async def _generate_poc_steps(self, finding: dict) -> list:
        """Generate basic PoC steps from finding data"""
        proof = finding.get("proof", {})
        url = proof.get("url", "")
        payload = proof.get("payload", "")

        basic_steps = [
            f"Navigate to: {url}" if url else "Navigate to the affected endpoint",
            f"Submit the following payload: {payload}" if payload else "Submit the test payload",
            "Observe the server response",
            "Note the vulnerable behavior as described above"
        ]
        return basic_steps
